language: java

jdk:
  - openjdk6
  
branches:
  only:
  - master

before_script:
 - chmod +x build.sh
  
script: "./build.sh"

env:
  global:
    secure: AS7hzxhq8Ur0J0ak2xFzqUc+fEn5IUkJ+CJkfWnO2mW83fKLlykqHudSoCV9RGmS+KMQTjcudII6HEwdzhWoPWwcX2cm2LFpgbMnJi+U97w/nMp8S/yzyh6pQT5dpqEAepSxc/cfN1H9yMqEUMrMeNBSGTDN8c44xgV9FAHx5BI=
