language: java

jdk:
  - oraclejdk8
node_js:
  - "0.10"
  
branches:
  only:
  - master

before_script:
  - npm install -g bower
  - bower install
install: true

script: mvn clean verify --settings ./settings.xml
